server:
  maxThreads: 200
  minThreads: 200
  maxQueuedRequests: 9999
  registerDefaultExceptionMappers: true
  requestLog:
      appenders: []
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 127.0.0.1 # only bind to loopback

database:
    driverClass:
        org.apache.derby.jdbc.EmbeddedDriver

    url:
        jdbc:derby:build/mydb;user=root;password=root;create=true
#    driverClass:
#        co.paralleluniverse.fibers.jdbc.FiberDriver
#
#    url:
#        jdbc:fiber:derby:build/mydb;user=root;password=root;create=true

    properties:
        charSet: UTF-8

    maxWaitForConnection: 1s
    user: root
    password: root

    validationQuery:
        "/* MyService Health Check */ VALUES 1"
#        "/* MyService Health Check */ SELECT 1"

    minSize: 8
    maxSize: 32
    checkConnectionWhileIdle: false

#logging:
#  level: INFO
#  appenders:
#    - type: file
#      currentLogFilename: C:/log/jdbc-instrumentation.log
#      threshold: ALL
#      archive: true
#      archivedLogFilenamePattern: C:/log/jdbc-instrumentation-%d.log
#      archivedFileCount: 5
#      timeZone: UTC
#      #logFormat: "%-30(%d{HH:mm:ss.SSS} [%thread]) %-5level %logger{32} - %msg%n"
#    - type: console
#      threshold: ALL
#      timeZone: UTC
#      target: stdout
