#Fiber HTTP Server config; queue'd requests are much higher since it's non blocking
server:
  maxThreads: 200
  minThreads: 200
  maxQueuedRequests: 9999
  registerDefaultExceptionMappers: true
  requestLog:
      appenders: []
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 127.0.0.1 # only bind to loopback


#Fiber HTTP Client configuration for async requests
httpClient:
    maxConnectionsPerRoute: 9999
    maxConnections: 9999

database:
    driverClass:
        org.apache.derby.jdbc.EmbeddedDriver

    url:
        jdbc:derby:build/mydb;user=root;password=root;create=true

    properties:
        charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
    maxWaitForConnection: 1s
    user: root
    password: root

  # the SQL query to run when validating a connection's liveness
    validationQuery:
        "/* MyService Health Check */ VALUES 1"
# for mysql use validationQuery such as this
#        "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
    minSize: 8

  # the maximum number of connections to keep open
    maxSize: 32

  # whether or not idle connections should be validated
    checkConnectionWhileIdle: false

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: C:/log/jdbc-instrumentation.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: C:/log/jdbc-instrumentation-%d.log
      archivedFileCount: 5
      timeZone: UTC
      #logFormat: "%-30(%d{HH:mm:ss.SSS} [%thread]) %-5level %logger{32} - %msg%n"
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
